image: ubuntu:bionic

job:
  before_script:
    - uname -a
    - apt-get update
    - apt-get install --yes cmake gcc g++ libgmp-dev
    - export CC=gcc
    - export CXX=g++
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make