dist: trusty
language: c
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
script:
  - export CC=gcc-7
  # Check versions of gcc and cmake
  - gcc-7 -v && cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1
