dist: xenial
language: c
compiler:
  - clang  
script:
  # Check versions of gcc and cmake
  - clang --version && cmake --version
  # build programs using cmake
  - mkdir build
  - cd build
  - cmake ..
  - make
