/* How many distinct terms are in the sequence generated by
 * a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100? Use 29.sh to get the answer.*/

#include <stdio.h>
#include <gmp.h>

#define MAXA 100
#define MAXB 100

void print(mpz_t powers[MAXA + 1][MAXB + 1])
{
	for (int a = 2; a <= MAXA; ++a) {
		for (int b = 2; b <= MAXB; ++b) {
			gmp_printf("%Zd\n", powers[a][b]);
		}
	}
}

int main()
{
	mpz_t powers[MAXA + 1][MAXB + 1];

	for (int a = 2; a <= MAXA; ++a) {
		for (int b = 2; b <= MAXB; ++b) {
			mpz_init(powers[a][b]);
			mpz_ui_pow_ui(powers[a][b],a,b); 
		}
	}

	print(powers);
	return 0;
}
