name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        uname -a
        sudo apt-get update
        sudo apt-get install --yes cmake gcc g++ libgmp-dev
        export CC=gcc
        export CXX=g++
    - name: build
      run: |
        mkdir build
        cd build
        cmake ..
        make
